import {useState,useEffect} from 'react';
import {Link,NavLink,useLocation} from 'react-router-dom';
import {ArrowUpRight,Menu,X,Search,AudioLines,ChevronRight,ShieldCheck} from 'lucide-react';
import {IconButton} from './Common';
import {Player} from './Player';
import {useMusic} from '../context/MusicContext';
export const Layout=({children})=>{
 const [menu,setMenu]=useState(false);const location=useLocation();const {current}=useMusic();
 useEffect(()=>{setMenu(false);window.scrollTo({top:0,behavior:'instant'});},[location.pathname]);
 const nav=[['/','Home'],['/discover','Discover'],['/playlists','My library'],['/contact','Contact']];
 return <div className={`site-shell ${current?'has-player':''}`}><header className="site-header"><div className="header-inner"><Link className="brand-link" to="/" aria-label="FLASHUBZ Music World home" data-testid="header-logo"><img src="/assets/flashubz-logo.webp" alt="FLASHUBZ"/><span>MUSIC WORLD</span></Link><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([url,name])=><NavLink key={url} end={url==='/'} to={url} data-testid={`nav-${name.toLowerCase().replace(' ','-')}`}>{name}</NavLink>)}</nav><div className="header-actions"><Link to="/discover?search=true" className="header-search" data-testid="header-search" aria-label="Search songs"><Search size={18}/></Link><span className="header-divider"/><Link to="/discover" className="outline-link" data-testid="header-enter-world">Enter the world <ArrowUpRight size={15}/></Link><IconButton label={menu?'Close navigation':'Open navigation'} testId="mobile-menu-toggle" onClick={()=>setMenu(!menu)} aria-expanded={menu} style={{display:undefined}}><span className="mobile-menu-icon">{menu?<X/>:<Menu/>}</span></IconButton></div></div>{menu&&<nav className="mobile-nav" aria-label="Mobile navigation" data-testid="mobile-navigation">{nav.map(([url,name])=><NavLink key={url} to={url} data-testid={`mobile-nav-${name.toLowerCase().replace(' ','-')}`}>{name}<ArrowUpRight size={17}/></NavLink>)}<NavLink to="/favorites" data-testid="mobile-nav-favorites">My favorites<ArrowUpRight size={17}/></NavLink></nav>}</header>
 <main key={location.pathname} className="route-content">{children}</main><footer className="site-footer"><div className="footer-top"><Link to="/" data-testid="footer-logo" className="brand-link"><img src="/assets/flashubz-logo.webp" alt="FLASHUBZ"/><span>MUSIC WORLD</span></Link><span data-testid="footer-tagline">INDEPENDENT SOUND. LIMITLESS WORLD.</span><Link to="/contact" data-testid="footer-contact" className="text-link">Let's connect <ArrowUpRight size={17}/></Link></div><div className="footer-bottom"><span data-testid="copyright">© {new Date().getFullYear()} FLASHUBZ MUSIC WORLD. All rights reserved.</span><div><span><i className="status-dot"/> MADE FOR THE MUSIC</span><Link to="/admin" data-testid="footer-admin" aria-label="Admin dashboard"><ShieldCheck size={14}/> Admin</Link></div></div></footer><Player/></div>;
};