import {useState} from 'react';
import {Copy,Check,Share2,Download,Send,MessageCircle,Loader2} from 'lucide-react';
import {toast} from 'sonner';
import {BASE} from '../lib/api';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {Button} from './ui/button';
const XIcon=({size=16})=><svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M18.244 2H21.5l-7.5 8.57L22.8 22h-6.9l-5.4-7.06L4.3 22H1.04l8.02-9.17L.6 2h7.07l4.88 6.45L18.24 2Zm-1.14 18h1.8L7 3.9H5.07L17.1 20Z"/></svg>;
export const ShareDialog=({open,onOpenChange,song})=>{
 const [copied,setCopied]=useState(false),[saving,setSaving]=useState(false);
 const url=`${BASE}/api/share/${song.slug}`,text=`${song.name} — ${song.artist} · FLASHUBZ MUSIC WORLD`;
 const copy=async()=>{try{await navigator.clipboard.writeText(url);setCopied(true);toast.success('Song link copied');setTimeout(()=>setCopied(false),2000);}catch{toast.error('Could not copy. Long-press the link to copy it.');}};
 const native=async()=>{try{await navigator.share({title:text,text,url});}catch(e){if(e.name!=='AbortError')toast.error('Sharing is not available here. Copy the link instead.');}};
 const story=async()=>{setSaving(true);try{const blob=await (await fetch(`${BASE}/api/share/${song.slug}/story.jpg`)).blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`FLASHUBZ-${song.slug}-story.jpg`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),4000);toast.success('Story card saved. Post it to Instagram or TikTok.');}catch{toast.error('Could not download the story card.');}finally{setSaving(false);}};
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent data-testid="share-dialog" className="app-dialog share-dialog"><DialogTitle data-testid="share-dialog-title">SHARE THIS FREQUENCY</DialogTitle><DialogDescription>This cinematic card appears wherever the link is shared.</DialogDescription><img data-testid="share-card-preview" className="share-card-preview" src={`${BASE}/api/share/${song.slug}/card.jpg`} alt={`${song.name} share card`} width="1200" height="630"/><div className="share-link"><span data-testid="share-link-url">{url}</span><button type="button" data-testid="share-copy-link" aria-label="Copy link" onClick={copy}>{copied?<Check size={15}/>:<Copy size={15}/>}</button></div><div className="share-targets"><a data-testid="share-whatsapp" href={`https://wa.me/?text=${encodeURIComponent(`${text}\n${url}`)}`} target="_blank" rel="noopener noreferrer"><MessageCircle size={16}/>WhatsApp</a><a data-testid="share-telegram" href={`https://t.me/share/url?url=${encodeURIComponent(url)}&text=${encodeURIComponent(text)}`} target="_blank" rel="noopener noreferrer"><Send size={16}/>Telegram</a><a data-testid="share-x" href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`} target="_blank" rel="noopener noreferrer"><XIcon/>X</a>{typeof navigator!=='undefined'&&navigator.share&&<button type="button" data-testid="share-native" onClick={native}><Share2 size={16}/>More…</button>}</div><Button variant="outline" className="share-story" data-testid="share-download-story" disabled={saving} onClick={story}>{saving?<Loader2 size={15} className="spin"/>:<Download size={15}/>}Download Story card for Instagram / TikTok</Button></DialogContent></Dialog>;
};
