import {useEffect,useState,useCallback} from 'react';
import {toast} from 'sonner';
import {Plus,Trash2,Pencil,Save,ListMusic,Users,Download,Mic2,ExternalLink} from 'lucide-react';
import {api,errorText} from '../../lib/api';
import {Button} from '../ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../ui/dialog';
import {Loading,IconButton} from '../Common';
export default function AdminManagement({section}){
 const [data,setData]=useState(null),[songs,setSongs]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState(null),[deleting,setDeleting]=useState(null);
 const load=useCallback(()=>api.get(section==='settings'?'/settings':`/admin/${section}`).then(r=>setData(r.data)).catch(e=>setError(errorText(e))),[section]);
 useEffect(()=>{load();if(section==='playlists')api.get('/admin/songs').then(r=>setSongs(r.data)).catch(e=>setError(errorText(e)));},[section,load]);
 const save=async e=>{e.preventDefault();setBusy(true);setError('');try{if(section==='settings')await api.put('/admin/settings',data);else if(edit.id)await api.put(`/admin/playlists/${edit.id}`,edit);else await api.post('/admin/playlists',edit);toast.success(section==='settings'?'Settings saved':'Playlist saved');setEdit(null);load();}catch(e){setError(errorText(e));}finally{setBusy(false);}};
 const remove=async()=>{setBusy(true);try{await api.delete(`/admin/playlists/${deleting.id}`);setDeleting(null);load();toast.success('Playlist deleted');}catch(e){toast.error(errorText(e));}finally{setBusy(false);}};
 if(!data&&!error)return <Loading/>;
 return <><header className="admin-page-heading with-action"><div><span className="eyebrow">FLASHUBZ CONTROL ROOM</span><h1 data-testid={`admin-${section}-title`}>{section.toUpperCase()}</h1><p>{section==='settings'?'Make the world yours.':section==='playlists'?'Your editorial collections.':section==='users'?'A listener-first experience. No accounts needed.':'Your music world, in detail.'}</p></div>{section==='playlists'&&<Button data-testid="admin-new-playlist" className="red-button" onClick={()=>setEdit({name:'',song_ids:[]})}><Plus size={16}/>New playlist</Button>}</header>{error&&<p role="alert" className="error" data-testid="admin-management-error">{error}</p>}
 {section==='settings'&&data&&<form className="settings-form" onSubmit={save}><span className="form-section-title">SOCIAL CONNECTIONS</span><label htmlFor="tiktok-setting">TIKTOK_PROFILE_URL<input data-testid="tiktok-setting-input" id="tiktok-setting" type="url" placeholder="Enter your exact TikTok profile URL" value={data.tiktok_profile_url||''} onChange={e=>setData({tiktok_profile_url:e.target.value})}/></label><p>The Contact page uses this exact profile. Leave it empty to keep the link hidden.</p><Button data-testid="save-settings" type="submit" className="red-button" disabled={busy}><Save size={16}/>{busy?'Saving…':'SAVE SETTINGS'}</Button></form>}
 {section==='users'&&data&&<div className="visitor-overview"><Users size={38} strokeWidth={1}/><h2 data-testid="visitor-mode-title">BROWSER-BASED LISTENER LIBRARIES</h2><p>Favorites and personal playlists stay in each listener's browser. There are no listener accounts or passwords to manage.</p><div className="visitor-stat"><strong data-testid="visitor-count">{data.visitors_with_favorites}</strong><span>Visitors with favorites</span></div></div>}
 {section==='artists'&&Array.isArray(data)&&(data.length?<div>{data.map((a,i)=><div className="management-row" key={a.name} data-testid={`artist-row-${i}`}><Mic2 size={22}/><div><strong>{a.name}</strong><p>{a.songs} songs</p></div><span>{a.plays} plays</span></div>)}</div>:<div className="admin-empty" data-testid="artists-empty"><Mic2 size={30}/><h2>ARTISTS WILL APPEAR HERE</h2><p>Artists are added automatically when you upload a release.</p></div>)}
 {section==='downloads'&&Array.isArray(data)&&(data.length?<div>{data.map(d=><div className="management-row" key={d.id} data-testid={`download-row-${d.id}`}><Download size={20}/><div><strong>{d.song_name}</strong><p>Authorized download</p></div><span>{new Date(d.created_at).toLocaleString()}</span></div>)}</div>:<div className="admin-empty" data-testid="downloads-empty"><Download size={30}/><h2>THE DOWNLOAD ARCHIVE</h2><p>Authorized downloads will be recorded here.</p></div>)}
 {section==='playlists'&&Array.isArray(data)&&(data.length?<div>{data.map(p=><div className="management-row" data-testid={`admin-playlist-${p.id}`} key={p.id}><ListMusic size={23}/><div><strong>{p.name}</strong><p>{p.song_ids.length} songs</p></div><IconButton label={`Edit ${p.name}`} testId={`edit-admin-playlist-${p.id}`} onClick={()=>setEdit(p)}><Pencil/></IconButton><IconButton label={`Delete ${p.name}`} testId={`delete-admin-playlist-${p.id}`} onClick={()=>setDeleting(p)}><Trash2/></IconButton></div>)}</div>:<div className="admin-empty" data-testid="admin-playlists-empty"><ListMusic size={30}/><h2>SET THE MOOD</h2><p>Build your first editorial playlist.</p></div>)}
 <Dialog open={!!edit} onOpenChange={()=>setEdit(null)}><DialogContent className="app-dialog" data-testid="admin-playlist-dialog"><DialogTitle>{edit?.id?'EDIT PLAYLIST':'NEW PLAYLIST'}</DialogTitle><DialogDescription>Pick a name and add tracks from your archive.</DialogDescription><form onSubmit={save}><input data-testid="admin-playlist-name" aria-label="Playlist name" placeholder="Playlist name" value={edit?.name||''} required maxLength="100" onChange={e=>setEdit({...edit,name:e.target.value})}/><div className="editorial-song-options">{songs.map(s=><label key={s.id}><input type="checkbox" data-testid={`editorial-select-${s.id}`} checked={edit?.song_ids.includes(s.id)||false} onChange={e=>setEdit({...edit,song_ids:e.target.checked?[...edit.song_ids,s.id]:edit.song_ids.filter(id=>id!==s.id)})}/><span>{s.name}</span></label>)}</div>{error&&<p className="error" data-testid="admin-playlist-error">{error}</p>}<Button className="red-button" data-testid="save-admin-playlist" type="submit" disabled={busy}>{busy?'Saving…':'Save playlist'}</Button></form></DialogContent></Dialog><Dialog open={!!deleting} onOpenChange={()=>setDeleting(null)}><DialogContent className="app-dialog" data-testid="admin-playlist-delete-dialog"><DialogTitle>DELETE PLAYLIST?</DialogTitle><DialogDescription>“{deleting?.name}” will be removed. Songs will remain in your archive.</DialogDescription><Button data-testid="confirm-delete-admin-playlist" className="red-button" disabled={busy} onClick={remove}>Delete playlist</Button></DialogContent></Dialog></>;
}