import {useEffect,useState} from 'react';
import {Send,ArrowUpRight,CheckCircle2,AudioLines} from 'lucide-react';
import {api,errorText} from '../lib/api';
import {PageHeading} from '../components/Common';
import {Button} from '../components/ui/button';
import {SEO} from '../components/SEO';
export default function Contact(){
 const [settings,setSettings]=useState({}),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[error,setError]=useState('');
 useEffect(()=>{api.get('/settings').then(r=>setSettings(r.data)).catch(()=>{});},[]);
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));try{await api.post('/contact',data);setSent(true);form.reset();}catch(e){setError(errorText(e));}finally{setBusy(false);}};
 return <div className="page content-width contact-page"><SEO title="Contact FLASHUBZ"/><PageHeading eyebrow="LET'S MAKE SOME NOISE" title={<>CONTACT <em>FLASHUBZ</em></>} description="Great things start with a conversation."/><div className="contact-layout"><section className="contact-copy"><div className="contact-symbol"><AudioLines size={48} strokeWidth={1}/></div><h2 data-testid="contact-subtitle">ON THE SAME<br/><em>FREQUENCY?</em></h2><p data-testid="contact-intro">Have a question, music request, collaboration idea, or need support?<br/><br/>Get in touch with FLASHUBZ MUSIC WORLD.</p><div className="social-section"><span className="eyebrow">FOLLOW FLASHUBZ</span><div className="tiktok-profile"><span className="tiktok-icon">♪</span><div><strong>TikTok</strong><p data-testid="tiktok-handle">@FLASHUBZ</p></div></div>{settings.tiktok_profile_url?<a className="outline-link" data-testid="tiktok-follow" href={settings.tiktok_profile_url} target="_blank" rel="noopener noreferrer">FOLLOW ON TIKTOK<ArrowUpRight size={17}/></a>:<span className="muted" data-testid="tiktok-not-configured">Our TikTok link is coming soon.</span>}</div></section><form className="contact-form" onSubmit={submit} data-testid="contact-form"><span className="eyebrow">DROP US A MESSAGE</span>{sent&&<div className="success-message" role="status" data-testid="contact-success"><CheckCircle2 size={20}/><div><strong>You're on our radar.</strong><p>Your message has reached FLASHUBZ. Thanks for getting in touch.</p></div></div>}<label htmlFor="contact-name">YOUR NAME</label><input data-testid="contact-name" id="contact-name" name="name" placeholder="What should we call you?" required minLength="2" maxLength="100"/><label htmlFor="contact-email">EMAIL ADDRESS</label><input data-testid="contact-email" id="contact-email" name="email" type="email" placeholder="you@example.com" required/><label htmlFor="contact-message">YOUR MESSAGE</label><textarea data-testid="contact-message" id="contact-message" name="message" rows="6" placeholder="Tell us what's on your mind…" required minLength="10" maxLength="5000"/>{error&&<p role="alert" className="error" data-testid="contact-error">{error}</p>}<Button type="submit" className="red-button" data-testid="contact-submit" disabled={busy}>{busy?'Sending…':'SEND MESSAGE'}<Send size={16}/></Button><p className="form-note">Your details stay between us. Always.</p></form></div></div>;
}