import {useState,useEffect,useRef} from 'react';
import {useSearchParams} from 'react-router-dom';
import {Search,X,ArrowLeft,ArrowRight,SlidersHorizontal,Music2} from 'lucide-react';
import {useSongs} from '../hooks/useSongs';
import {SongFolder} from '../components/SongFolder';
import {PageHeading,EmptyState,Loading} from '../components/Common';
import {SEO} from '../components/SEO';
import {Button} from '../components/ui/button';
export default function Discover(){
 const [params]=useSearchParams();const [query,setQuery]=useState(''),[q,setQ]=useState(''),[sort,setSort]=useState('newest'),[page,setPage]=useState(1);const input=useRef();
 useEffect(()=>{const timer=setTimeout(()=>{setQ(query);setPage(1);},220);return()=>clearTimeout(timer);},[query]);
 useEffect(()=>{if(params.get('search'))input.current?.focus();},[params]);
 const {songs,total,pages,loading,error,reload}=useSongs({q,sort,page,limit:12});
 return <div className="content-width page discover-page"><SEO title="Discover Our Music"/><PageHeading eyebrow="THE FLASHUBZ ARCHIVE" title={<>DISCOVER OUR <em>MUSIC</em></>} description="Explore the FLASHUBZ Music World"><span className="archive-count" data-testid="archive-song-count"><Music2 size={16}/>{String(total).padStart(2,'0')} SONGS IN THE WORLD</span></PageHeading><div className="discovery-toolbar"><div className="search-field"><Search size={19}/><input ref={input} data-testid="search-songs" aria-label="Search songs, artists, albums, genres or languages" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search songs, artists, albums…"/>{query&&<button data-testid="clear-search" aria-label="Clear search" onClick={()=>setQuery('')}><X size={16}/></button>}</div><label className="sort-field"><SlidersHorizontal size={15}/><select data-testid="sort-songs" aria-label="Sort songs" value={sort} onChange={e=>{setSort(e.target.value);setPage(1);}}><option value="newest">Latest releases</option><option value="popular">Most played</option><option value="az">A — Z</option></select></label></div><div className="archive-section-label"><span data-testid="archive-results-label">{q?`RESULTS FOR “${q}”`:'ALL FREQUENCIES'}</span><span>ONE SONG. ONE WORLD.</span></div>{loading?<Loading/>:error?<div className="empty-state" data-testid="discover-error"><p>{error}</p><Button data-testid="discover-retry" onClick={reload}>Try again</Button></div>:songs.length?<div className="folder-grid">{songs.map((s,i)=><SongFolder key={s.id} song={s} index={(page-1)*12+i} queue={songs}/>)}</div>:<EmptyState title={q?'NO MATCHING FREQUENCIES':'THE FIRST DROP IS COMING'} description={q?'Try another song, artist, album, genre, or language.':'The FLASHUBZ archive is getting ready for its first release. Stay close.'} action={!q}/>} {pages>1&&<div className="pagination"><Button variant="outline" data-testid="songs-previous-page" disabled={page<=1} onClick={()=>setPage(page-1)}><ArrowLeft size={16}/>Previous</Button><span data-testid="songs-pagination">{page} / {pages}</span><Button variant="outline" data-testid="songs-next-page" disabled={page>=pages} onClick={()=>setPage(page+1)}>Next<ArrowRight size={16}/></Button></div>}</div>;
}