import {lazy,Suspense} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {ArrowRight,ArrowUpRight,ArrowDown,Play,Pause,AudioLines,Headphones,Heart,ListMusic,Disc3} from 'lucide-react';
import {useMusic} from '../context/MusicContext';
import {useSongs} from '../hooks/useSongs';
import {Waveform} from '../components/Waveform';
import {SongFolder} from '../components/SongFolder';
import {SEO} from '../components/SEO';
const WorldScene=lazy(()=>import('../components/WorldScene'));
export default function Home(){
 const m=useMusic(),navigate=useNavigate();const {songs}=useSongs({limit:4});
 const orbClick=()=>{if(m.current)m.toggle();else if(songs.length)m.playSong(songs[0],songs);else navigate('/discover');};
 return <><SEO/><section className="hero" data-testid="home-hero"><div className="hero-atmosphere"/><Suspense fallback={<div className="scene-loading"/>}><WorldScene onOrbClick={orbClick}/></Suspense><div className="hero-inner"><div className="hero-copy"><div className="hero-eyebrow" data-testid="hero-eyebrow"><span className="status-dot"/> NOT JUST MUSIC. A WHOLE NEW WORLD.</div><h1 className="hero-brand" data-testid="hero-title"><img src="/assets/flashubz-logo.webp" alt="FLASHUBZ"/><span className="music-world-line"><Waveform bars={16}/><span>MUSIC <em>WORLD</em></span><Waveform bars={16}/></span></h1><p data-testid="hero-description" className="hero-description">Feel the sound. Find your frequency.<br/>Step into the world of FLASHUBZ.</p><Link data-testid="discover-our-pages" className="discover-button" to="/discover"><span className="cta-play"><Play size={13} fill="currentColor"/></span>DISCOVER OUR PAGES<ArrowRight size={15}/></Link><div className="hero-smallprint"><span/><span>TURN IT UP. THIS IS YOUR WORLD.</span></div></div></div><button data-testid="hero-orb-play" className="orb-accessible-control" aria-label={m.playing?'Pause music':'Play music'} onClick={orbClick}>{m.playing?<Pause size={13}/>:<Play size={13}/>}<span>{m.playing?'PAUSE THE FREQUENCY':'PRESS PLAY. FEEL EVERYTHING.'}</span></button><div className="hero-bottom"><span data-testid="hero-index"><b>01</b> / ENTER THE WORLD</span><button data-testid="hero-scroll" onClick={()=>document.getElementById('latest').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}>SCROLL TO EXPLORE <ArrowDown size={13}/></button><span className="sound-indicator" data-testid="hero-sound-status"><AudioLines size={15}/>{m.playing?'SOUND ON':'SOUND OFF'}</span></div></section>
 <section className="home-archive content-width" id="latest"><div className="section-heading"><div><span className="eyebrow">FRESH FROM THE WORLD</span><h2 data-testid="latest-heading">THE LATEST <em>FREQUENCIES.</em></h2></div><Link to="/discover" className="text-link" data-testid="view-all-music">Explore all music <ArrowUpRight size={16}/></Link></div>{songs.length?<div className="folder-grid home-folders">{songs.map((s,i)=><SongFolder key={s.id} song={s} index={i} queue={songs}/>)}</div>:<div className="first-drop"><div className="first-drop-icon"><Disc3 strokeWidth={1}/></div><div><span className="eyebrow">THE ARCHIVE STARTS HERE</span><h3 data-testid="first-drop-heading">Something worth turning up.</h3><p data-testid="first-drop-description">The first FLASHUBZ releases are on their way. Be part of what's next.</p></div><Link data-testid="first-drop-connect" to="/contact" className="outline-link">Stay in the loop <ArrowUpRight size={16}/></Link><span className="first-drop-watermark" aria-hidden="true">001</span></div>}</section>
 <section className="world-links content-width"><Link to="/discover" data-testid="portal-discover"><Headphones/><span><small>01 / THE ARCHIVE</small><strong>Find your next obsession.</strong></span><ArrowUpRight/></Link><Link to="/favorites" data-testid="portal-favorites"><Heart/><span><small>02 / YOUR FAVORITES</small><strong>Keep what moves you.</strong></span><ArrowUpRight/></Link><Link to="/playlists" data-testid="portal-playlists"><ListMusic/><span><small>03 / YOUR PLAYLISTS</small><strong>Make the world your own.</strong></span><ArrowUpRight/></Link></section></>;
}