import {useState} from 'react';
import {Link,useParams,useNavigate} from 'react-router-dom';
import {Heart,Plus,ListMusic,ArrowUpRight,Play,Trash2,Pencil,ArrowLeft,X} from 'lucide-react';
import {toast} from 'sonner';
import {useMusic} from '../context/MusicContext';
import {useSongs} from '../hooks/useSongs';
import {useLibrarySongs} from '../hooks/useLibrarySongs';
import {PageHeading,EmptyState,Loading,Cover,IconButton} from '../components/Common';
import {SongFolder} from '../components/SongFolder';
import {PlaylistDialog} from '../components/PlaylistDialog';
import {Button} from '../components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../components/ui/dialog';
import {SEO} from '../components/SEO';
export default function Library({favorites=false}){
 const m=useMusic();const [creating,setCreating]=useState(false),[page,setPage]=useState(1);const {songs,pages,loading,error}=useSongs({ids:m.favorites.length?m.favorites.join(','):'none',limit:12,page});
 return <div className="page content-width"><SEO title={favorites?'My Favorites':'My Playlists'}/><PageHeading eyebrow="YOUR PERSONAL FREQUENCY" title={favorites?<>MY <em>FAVORITES</em></>:<>MY <em>PLAYLISTS</em></>} description={favorites?'The music that stays with you.':'A soundtrack for every side of you.'}>{!favorites&&<Button data-testid="new-playlist" className="red-button" onClick={()=>setCreating(true)}><Plus size={17}/>New playlist</Button>}</PageHeading><div className="content-tabs library-tabs"><Link data-testid="library-playlists-tab" className={!favorites?'active':''} to="/playlists"><ListMusic size={16}/>Playlists <span>{m.playlists.length}</span></Link><Link data-testid="library-favorites-tab" className={favorites?'active':''} to="/favorites"><Heart size={16}/>Favorites <span>{m.favorites.length}</span></Link><span className="browser-label" data-testid="library-storage-note">SAVED ON THIS BROWSER</span></div>{favorites?(loading?<Loading/>:error?<p className="error" data-testid="favorites-error">{error}</p>:songs.length?<><div className="folder-grid">{songs.map((s,i)=><SongFolder key={s.id} song={s} index={i} queue={songs}/>)}</div>{pages>1&&<div className="pagination"><Button data-testid="favorites-prev" disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</Button><span>{page} / {pages}</span><Button data-testid="favorites-next" disabled={page>=pages} onClick={()=>setPage(page+1)}>Next</Button></div>}</>:<EmptyState title="KEEP WHAT MOVES YOU" description="Your favorite tracks will have a home right here." action={false}/>):m.playlists.length?<div className="playlist-grid">{m.playlists.map((p,i)=><Link to={`/playlist/${p.id}`} data-testid={`playlist-${p.id}`} key={p.id} className="playlist-item"><div className="playlist-visual"><ListMusic strokeWidth={1}/><span>{String(i+1).padStart(2,'0')}</span></div><div><h2 data-testid={`playlist-name-${p.id}`}>{p.name}</h2><p>{p.song_ids.length} songs</p><ArrowUpRight size={20}/></div></Link>)}</div>:<EmptyState title="YOUR WORLD. YOUR ORDER." description="Start a playlist and make room for your next favorite sound." action={false}/>}<PlaylistDialog open={creating} onOpenChange={setCreating}/></div>;
}
export function PlaylistPage(){
 const {id}=useParams(),m=useMusic(),navigate=useNavigate();const playlist=m.playlists.find(p=>p.id===id);const [dialog,setDialog]=useState(''),[name,setName]=useState(playlist?.name||'');const {songs,loading,error}=useLibrarySongs(playlist?.song_ids||[]);
 if(!playlist)return <div className="page content-width"><EmptyState title="PLAYLIST NOT FOUND" description="This playlist isn't saved on this browser." action={false}/><Link className="text-link" data-testid="playlist-not-found-back" to="/playlists">Back to your library</Link></div>;
 const ordered=playlist.song_ids.map(sid=>songs.find(s=>s.id===sid)).filter(Boolean);
 const remove=song=>{m.updatePlaylists(old=>old.map(p=>p.id===id?{...p,song_ids:p.song_ids.filter(s=>s!==song.id)}:p));toast.success('Song removed from playlist');};
 const submit=e=>{e.preventDefault();if(dialog==='delete'){m.updatePlaylists(old=>old.filter(p=>p.id!==id));navigate('/playlists');toast.success('Playlist deleted');}else if(name.trim()){m.updatePlaylists(old=>old.map(p=>p.id===id?{...p,name:name.trim()}:p));setDialog('');toast.success('Playlist renamed');}};
 return <div className="page content-width"><SEO title={playlist.name}/><Link to="/playlists" className="text-link back-link" data-testid="playlist-back"><ArrowLeft size={15}/>Your library</Link><PageHeading eyebrow="YOUR PERSONAL PLAYLIST" title={playlist.name} description={`${playlist.song_ids.length} songs · Saved on this browser`}><div className="row-actions"><Button data-testid="playlist-play" className="red-button" disabled={!ordered.length} onClick={()=>m.playSong(ordered[0],ordered)}><Play size={15}/>Play playlist</Button><IconButton label="Rename playlist" testId="playlist-rename" onClick={()=>setDialog('rename')}><Pencil/></IconButton><IconButton label="Delete playlist" testId="playlist-delete" onClick={()=>setDialog('delete')}><Trash2/></IconButton></div></PageHeading>{loading?<Loading/>:error?<p className="error" data-testid="playlist-error">{error}</p>:ordered.length?<div className="track-list">{ordered.map((s,i)=><div className="track-row" data-testid={`playlist-track-${s.id}`} key={s.id}><span className="track-index">{String(i+1).padStart(2,'0')}</span><Cover song={s}/><Link to={`/song/${s.slug}`} data-testid={`playlist-track-link-${s.id}`}><strong>{s.name}</strong><span>{s.artist}</span></Link><IconButton label={`Play ${s.name}`} testId={`playlist-track-play-${s.id}`} onClick={()=>m.playSong(s,ordered)}><Play/></IconButton><IconButton label={`Remove ${s.name}`} testId={`playlist-track-remove-${s.id}`} onClick={()=>remove(s)}><X/></IconButton></div>)}</div>:<EmptyState title="ROOM FOR YOUR NEXT OBSESSION" description="Find your sound in Discover, then add it to this playlist." action={false}/>}<Link className="text-link" to="/discover" data-testid="playlist-add-music">Find more music <ArrowUpRight size={17}/></Link><Dialog open={!!dialog} onOpenChange={()=>setDialog('')}><DialogContent data-testid="playlist-edit-dialog" className="app-dialog"><DialogTitle>{dialog==='delete'?'DELETE PLAYLIST?':'RENAME PLAYLIST'}</DialogTitle><DialogDescription>{dialog==='delete'?'This removes the playlist from this browser. Your favorites will stay.':'Give your soundtrack a new name.'}</DialogDescription><form onSubmit={submit}>{dialog==='rename'&&<input data-testid="playlist-rename-input" value={name} aria-label="Playlist name" onChange={e=>setName(e.target.value)} required maxLength="100"/>}<Button data-testid="playlist-confirm-action" className="red-button" type="submit">{dialog==='delete'?'Delete playlist':'Save name'}</Button></form></DialogContent></Dialog></div>;
}